name: Angular Docker CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Angular application
        run: npm run build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        run: az acr login --name rohitangularacr2026

      - name: Build Docker image
        run: |
          docker build \
            -t rohitangularacr2026.azurecr.io/docker-angular-app:${{ github.sha }} \
            -t rohitangularacr2026.azurecr.io/docker-angular-app:latest \
            .

      - name: Push Docker image to ACR
        run: |
          docker push rohitangularacr2026.azurecr.io/docker-angular-app:${{ github.sha }}
          docker push rohitangularacr2026.azurecr.io/docker-angular-app:latest

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: rg-docker-angular
          containerAppName: docker-angular-app
          imageToDeploy: rohitangularacr2026.azurecr.io/docker-angular-app:${{ github.sha }}
